version: "3.8"

services:
  bot:
    build:
      context: .
#    command: |
#      sh -c
#      'poetry run alembic upgrade head &&
#      poetry run python app/main.py'
    environment:
      DATABASES_DSN: postgresql+asyncpg://bot-user:example@bot-db:5432/bot
      CACHE_DSN: redis://default:redis@bot-redis:6379/3
    volumes:
      - .:/src
    ports:
      - 8061:8061
    depends_on:
      - bot-db
      - bot-redis

  bot-db:
    image: postgres:15-alpine3.16
    command: [ "postgres", "-c", "log_statement=all", "-c", "log_destination=stderr" ]
#    volumes:
#      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: bot-user
      POSTGRES_PASSWORD: example
      POSTGRES_DB: bot

  bot-redis:
    image: eqalpha/keydb:x86_64_v6.3.2
    command: keydb-server --maxmemory 64m --maxmemory-policy noeviction --requirepass 'redis'
    ports:
      - 6379:6379
