version: "3.8"

services:
  bot:
    build:
      context: .
    environment:
      DATABASES_DSN: postgresql+asyncpg://bot-user:example@bot-db:5432/test
    volumes:
      - .:/src
    depends_on:
      - bot-db

  bot-db:
    image: postgres:15-alpine3.16
    command: [ "postgres", "-c", "log_statement=all", "-c", "log_destination=stderr" ]
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: bot-user
      POSTGRES_PASSWORD: example
      POSTGRES_DB: test

  bot-redis:
    image: eqalpha/keydb:x86_64_v6.3.2
    command: keydb-server --maxmemory 64m --maxmemory-policy noeviction --requirepass 'redis'
    ports:
      - 6379:6379
