[tool.poetry]
name = "chat_template"
version = "0.1.0"
description = ""
authors = ["innokentiyzabirov"]

[tool.poetry.dependencies]
python = "^3.11"
fastapi = "^0.100.0"
python-socketio = "^5.8.0"
uvicorn = "0.20.0"
uvloop = "0.17.0"
loguru = "^0.6.0"
redis = "4.5.5"
sqlalchemy = "2.0.6"
asyncpg = "^0.27.0"
alembic = "^1.10.3"
httpx = "^0.24.0"
pydantic = "^2.0.2"
pydantic-settings = "^2.0.1"

[tool.poetry.group.dev.dependencies]
pre-commit = "^3.2.2"
black = "^23.3.0"
python-socketio = {version = "^5.8.0", extras = ["asyncio-client"]}
requests = "^2.28.2"
isort = "^5.12.0"
pytest = "^7.3.1"
pytest-asyncio = "^0.21.0"
pytest-factoryboy = "^2.5.1"
mypy = "^1.3.0"
types-redis = "^4.6.0.1"
polyfactory = "^2.6.1"
pytest-mock = "^3.11.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 119
target-version = ['py311']
include = '\.pyi?$'
# 'extend-exclude' excludes files or directories in addition to the defaults
extend-exclude = '''
# A regex preceded with ^/ will apply only to files and directories
# in the root of the project.
(
  ^/foo.py    # exclude a file named foo.py in the root of the project
  | .*_pb2.py  # exclude autogenerated Protocol Buffer files anywhere in the project
)
'''

[tool.isort]
profile = "black"
extend_skip = ["alembic"]

[tool.mypy]
python_version = "3.11"
disallow_untyped_defs = true
ignore_missing_imports = true
disable_error_code = "attr-defined"

[tool.pytest.ini_options]
asyncio_mode = "auto"
