"""empty message

Revision ID: 9c10d536a11c
Revises: 
Create Date: 2023-04-22 12:18:30.912601

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "9c10d536a11c"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "chats", sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False), sa.PrimaryKeyConstraint("id")
    )
    op.create_table(
        "users",
        sa.Column("uid", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=256), nullable=False),
        sa.Column("is_blocked", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("uid"),
    )
    op.create_index(op.f("ix_users_uid"), "users", ["uid"], unique=False)
    op.create_table(
        "chats_relationships",
        sa.Column("user_uid", sa.UUID(), nullable=False),
        sa.Column("chat_id", sa.BigInteger(), nullable=False),
        sa.Column("chat_name", sa.String(length=256), nullable=False),
        sa.Column(
            "state",
            sa.Enum("ACTIVE", "FOR_FAVORITE", "ARCHIVE", "FAVORITE", "DELETED", name="chatstate"),
            nullable=False,
        ),
        sa.Column("is_admin", sa.Boolean(), nullable=True),
        sa.Column("last_read_message_id", sa.BigInteger(), nullable=True),
        sa.Column("unread_counter", sa.Integer(), nullable=True),
        sa.Column("is_pinned", sa.Boolean(), nullable=True),
        sa.Column(
            "user_role", sa.Enum("CREATOR", "ADMIN", "USER", "ONLY_FOR_DATA", name="chatuserrole"), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["chat_id"],
            ["chats.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_uid"],
            ["users.uid"],
        ),
        sa.PrimaryKeyConstraint("user_uid", "chat_id", name="chats_relationships_pk"),
    )
    op.create_index(op.f("ix_chats_relationships_chat_id"), "chats_relationships", ["chat_id"], unique=False)
    op.create_index(op.f("ix_chats_relationships_user_uid"), "chats_relationships", ["user_uid"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_chats_relationships_user_uid"), table_name="chats_relationships")
    op.drop_index(op.f("ix_chats_relationships_chat_id"), table_name="chats_relationships")
    op.drop_table("chats_relationships")
    op.drop_index(op.f("ix_users_uid"), table_name="users")
    op.drop_table("users")
    op.drop_table("chats")
    sa.Enum(name="chatuserrole").drop(op.get_bind())
    sa.Enum(name="chatstate").drop(op.get_bind())
    # ### end Alembic commands ###
