"""empty message

Revision ID: fb96666c35ca
Revises: 0c8a572c5131
Create Date: 2023-05-21 08:03:10.073151

"""
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "fb96666c35ca"
down_revision = "0c8a572c5131"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "messages",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("user_uid", sa.UUID(), nullable=True),
        sa.Column("chat_id", sa.BigInteger(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("search_text", postgresql.TSVECTOR(), nullable=False),
        sa.Column("type_", sa.Enum("FROM_USER", "SYSTEM", "DELETED", name="messagetype"), nullable=False),
        sa.Column("quoted_message", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("mentions", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("links", postgresql.ARRAY(sa.String(length=1000)), nullable=False),
        sa.Column("original_id", sa.BigInteger(), nullable=False),
        sa.Column("original_chat_id", sa.BigInteger(), nullable=False),
        sa.Column("time_created", sa.DateTime(), nullable=False),
        sa.Column("time_updated", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["chat_id"],
            ["chats.id"],
        ),
        sa.ForeignKeyConstraint(
            ["original_chat_id"],
            ["chats.id"],
        ),
        sa.ForeignKeyConstraint(
            ["original_id"],
            ["messages.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_uid"],
            ["users.uid"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_messages_chat_id"), "messages", ["chat_id"], unique=False)
    op.create_index(op.f("ix_messages_user_uid"), "messages", ["user_uid"], unique=False)
    op.create_index("search_by_message_text", "messages", ["search_text"], unique=False, postgresql_using="gin")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("search_by_message_text", table_name="messages", postgresql_using="gin")
    op.drop_index(op.f("ix_messages_user_uid"), table_name="messages")
    op.drop_index(op.f("ix_messages_chat_id"), table_name="messages")
    op.drop_table("messages")
    sa.Enum(name="messagetype").drop(op.get_bind())
    # ### end Alembic commands ###
