"""empty message

Revision ID: cab491b47f97
Revises: fb96666c35ca
Create Date: 2023-06-07 19:26:29.274310

"""
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "cab491b47f97"
down_revision = "fb96666c35ca"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("messages", "quoted_message", existing_type=postgresql.JSONB(astext_type=sa.Text()), nullable=True)
    op.alter_column("messages", "mentions", existing_type=postgresql.JSONB(astext_type=sa.Text()), nullable=True)
    op.alter_column("messages", "links", existing_type=postgresql.ARRAY(sa.VARCHAR(length=1000)), nullable=True)
    op.alter_column("messages", "original_id", existing_type=sa.BIGINT(), nullable=True)
    op.alter_column("messages", "original_chat_id", existing_type=sa.BIGINT(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("messages", "original_chat_id", existing_type=sa.BIGINT(), nullable=False)
    op.alter_column("messages", "original_id", existing_type=sa.BIGINT(), nullable=False)
    op.alter_column("messages", "links", existing_type=postgresql.ARRAY(sa.VARCHAR(length=1000)), nullable=False)
    op.alter_column("messages", "mentions", existing_type=postgresql.JSONB(astext_type=sa.Text()), nullable=False)
    op.alter_column(
        "messages", "quoted_message", existing_type=postgresql.JSONB(astext_type=sa.Text()), nullable=False
    )
    # ### end Alembic commands ###
