"""empty message

Revision ID: 547150faf467
Revises: d31df410d013
Create Date: 2023-07-15 14:26:43.124860

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "547150faf467"
down_revision = "d31df410d013"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("chats_relationships", sa.Column("time_pinned", sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("chats_relationships", "time_pinned")
    # ### end Alembic commands ###
