"""empty message

Revision ID: 3f191fbba15a
Revises: d31df410d013
Create Date: 2023-07-16 11:30:05.835836

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "3f191fbba15a"
down_revision = "d31df410d013"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("chats_relationships", sa.Column("time_pinned", sa.DateTime(), nullable=True))
    op.drop_column("chats_relationships", "is_pinned")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("chats_relationships", sa.Column("is_pinned", sa.BOOLEAN(), nullable=False))
    op.drop_column("chats_relationships", "time_pinned")
    # ### end Alembic commands ###
