"""empty message

Revision ID: 4a7a05f47a6f
Revises: 3f191fbba15a
Create Date: 2023-08-27 10:02:54.779663

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "4a7a05f47a6f"
down_revision = "3f191fbba15a"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "devices",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("user_uid", sa.UUID(), nullable=True),
        sa.Column("token", sa.String(length=256), nullable=False),
        sa.Column("platform", sa.String(length=32), nullable=False),
        sa.Column("time_created", sa.DateTime(), nullable=False),
        sa.Column("time_updated", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_uid"],
            ["users.uid"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_uid", "platform", name="uqp_user_uid_platform"),
    )
    op.create_index(op.f("ix_devices_user_uid"), "devices", ["user_uid"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_devices_user_uid"), table_name="devices")
    op.drop_table("devices")
    # ### end Alembic commands ###
